name: sign_learning_server
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi
    - uvicorn
    - sqlalchemy
    - python-dotenv
    - python-jose
    - passlib
    - bcrypt
    - pyodbc
    - mediapipe
    - opencv-python
    - numpy